name: Go build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build (linux x86-64)
        run: env GOOS=linux GOARCH=amd64 go build -v ./... && tar -cvf mmp-linux-x86-64.tar mmp

      - name: Build (macOS x86-64)
        run: env GOOS=darwin GOARCH=amd64 go build -v ./... && tar -cvf mmp-macos-intel.tar mmp

      - name: Build (macOS ARM)
        run: env GOOS=darwin GOARCH=arm64 go build -v ./... && tar -cvf mmp-macos-arm64.tar mmp

      - name: Test
        run: go test -v ./...
      
      - uses: actions/upload-artifact@v3
        with:
          name: mmp-linux-x86-64.tar
          path: mmp-linux-x86-64.tar
      
      - uses: actions/upload-artifact@v3
        with:
          name: mmp-macos-intel.tar
          path: mmp-macos-intel.tar
      
      - uses: actions/upload-artifact@v3
        with:
          name: mmp-macos-arm64.tar
          path: mmp-macos-arm64.tar
