name: Go build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build (linux x86-64)
        run: env GOOS=linux GOARCH=amd64 go build -v ./... && mv mmp mmp-linux-x86-64

      - name: Build (macOS x86-64)
        run: env GOOS=darwin GOARCH=amd64 go build -v ./... && mv mmp mmp-macos-intel

      - name: Build (macOS ARM)
        run: env GOOS=darwin GOARCH=arm64 go build -v ./... && mv mmp mmp-macos-arm64

      - name: Test
        run: go test -v ./...
      
      - uses: actions/upload-artifact@v3
        with:
          name: mmp
          path: mmp-*
