name: Test

on: push

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache-dependency-path: src/go.sum

      - name: Running end-to-end tests
        run: |
          for test_file in tests/test_*/run.sh; do
            echo "/// Running test for $test_file ///"
            bash $test_file
          done
